"""Image helper for build-poetry-site.ps1. Pillow only (already installed on the build host).

Subcommands
  encode --jobs <json>   Re-rasterise each source PNG into a fresh RGB buffer and write a full-size
                         and a thumbnail WebP. The fresh buffer carries no `info` dict, so no PNG
                         ancillary chunk (tEXt/iTXt/zTXt/iCCP/eXIf) can be copied through. Prints one
                         JSON line per job.
  chunks <file>          Print the chunk list of a PNG (chunk types) or WebP (RIFF fourCCs) as JSON.
                         Used by the acceptance-gate harness to assert on the generated bytes.
  plant <src> <dst> <key> <text>
                         Copy a PNG adding a tEXt chunk. Test fixture only (plants a canary).

This file NEVER enumerates a directory. It touches exactly the paths it is handed.
"""
import json
import struct
import sys

from PIL import Image, PngImagePlugin


def _fresh_rgb(path):
    im = Image.open(path)
    im.load()
    src_text = sorted(k for k in im.info.keys() if k not in ("dpi", "gamma", "transparency", "interlace"))
    fresh = Image.new("RGB", im.size)
    fresh.paste(im.convert("RGB"))
    return fresh, im.size, src_text


def cmd_encode(jobs_path):
    with open(jobs_path, "r", encoding="utf-8") as fh:
        jobs = json.load(fh)
    if isinstance(jobs, dict):
        jobs = [jobs]
    for j in jobs:
        base = j["full"].replace("\\", "/").rsplit("/", 1)[-1][: -len(".webp")]
        fresh, (sw, sh), src_text = _fresh_rgb(j["src"])
        q = int(j.get("quality", 82))

        full = fresh.copy()
        full.thumbnail((int(j["max_full"]), int(j["max_full"])), Image.LANCZOS)
        # Pillow 12 WebPImagePlugin._save (lines 287-293) reads icc_profile / exif / xmp from
        # im.encoderinfo -- the save() kwargs -- and never from im.info. We pass none, and `fresh`
        # was built with Image.new so it carries no info either. The gate harness asserts this on
        # the emitted bytes (RIFF chunk list) rather than trusting the reading.
        full.save(j["full"], "WEBP", quality=q, method=6)

        thumb = fresh.copy()
        thumb.thumbnail((int(j["max_thumb"]), int(j["max_thumb"])), Image.LANCZOS)
        thumb.save(j["thumb"], "WEBP", quality=q, method=6)

        import os
        print(json.dumps({
            "base": base,
            "src_w": sw, "src_h": sh, "src_text_chunks": src_text,
            "full_w": full.size[0], "full_h": full.size[1], "full_bytes": os.path.getsize(j["full"]),
            "thumb_w": thumb.size[0], "thumb_h": thumb.size[1], "thumb_bytes": os.path.getsize(j["thumb"]),
        }, sort_keys=True))
    return 0


def png_chunks(data):
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    out, pos = [], 8
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        ctype = data[pos + 4:pos + 8].decode("latin-1")
        out.append(ctype)
        pos += 12 + length
    return out


def webp_chunks(data):
    if data[:4] != b"RIFF" or data[8:12] != b"WEBP":
        raise ValueError("not a WebP")
    out, pos = [], 12
    while pos + 8 <= len(data):
        fourcc = data[pos:pos + 4].decode("latin-1")
        size = struct.unpack("<I", data[pos + 4:pos + 8])[0]
        out.append(fourcc.rstrip())
        pos += 8 + size + (size & 1)
    return out


def cmd_chunks(path):
    with open(path, "rb") as fh:
        data = fh.read()
    if data[:4] == b"RIFF":
        kind, chunks = "webp", webp_chunks(data)
    else:
        kind, chunks = "png", png_chunks(data)
    print(json.dumps({"file": path, "kind": kind, "chunks": chunks, "bytes": len(data)}))
    return 0


def cmd_plant(src, dst, key, text):
    im = Image.open(src)
    im.load()
    meta = PngImagePlugin.PngInfo()
    meta.add_text(key, text)
    im.save(dst, "PNG", pnginfo=meta)
    print(json.dumps({"planted": dst, "key": key}))
    return 0


def main(argv):
    if len(argv) >= 3 and argv[0] == "encode" and argv[1] == "--jobs":
        return cmd_encode(argv[2])
    if len(argv) == 2 and argv[0] == "chunks":
        return cmd_chunks(argv[1])
    if len(argv) == 5 and argv[0] == "plant":
        return cmd_plant(argv[1], argv[2], argv[3], argv[4])
    sys.stderr.write(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
