"""Image helper for build-poetry-site.ps1. Pillow only (already installed on the build host).

Subcommands
  encode --jobs <json>   Re-rasterise each source PNG into a fresh RGB buffer and write a full-size
                         and a thumbnail WebP. The fresh buffer carries no `info` dict, so no PNG
                         ancillary chunk (tEXt/iTXt/zTXt/iCCP/eXIf) can be copied through. Prints one
                         JSON line per job.
  chunks <file>          Print the chunk list of a PNG (chunk types) or WebP (RIFF fourCCs) as JSON.
                         Used by the acceptance-gate harness to assert on the generated bytes.
  plant <src> <dst> <key> <text>
                         Copy a PNG adding a tEXt chunk. Test fixture only (plants a canary).
  pair --jobs <json>     Comparison pairs (0.3.0). Re-encode BOTH images of each pair through one
                         identical pipeline: decode -> apply EXIF orientation -> convert any embedded
                         ICC profile to sRGB -> RGB -> centre-crop/resize to the SAME target size ->
                         fresh buffer -> WebP at the same quality. Nothing from either source's info
                         dict (EXIF, XMP, C2PA/caBX, ICC, text) is passed to save().
  plant-provenance <src> <dst> <w> <h> <label>
                         Test fixture only: write a "ChatGPT-like" PNG (resized to w x h) carrying a
                         tEXt label, an eXIf block, an XMP iTXt packet, an iCCP profile and a C2PA
                         caBX chunk, each containing <label>.

This file NEVER enumerates a directory. It touches exactly the paths it is handed.
"""
import json
import struct
import sys

from PIL import Image, PngImagePlugin


def _fresh_rgb(path):
    im = Image.open(path)
    im.load()
    src_text = sorted(k for k in im.info.keys() if k not in ("dpi", "gamma", "transparency", "interlace"))
    fresh = Image.new("RGB", im.size)
    fresh.paste(im.convert("RGB"))
    return fresh, im.size, src_text


def cmd_encode(jobs_path):
    with open(jobs_path, "r", encoding="utf-8") as fh:
        jobs = json.load(fh)
    if isinstance(jobs, dict):
        jobs = [jobs]
    for j in jobs:
        base = j["full"].replace("\\", "/").rsplit("/", 1)[-1][: -len(".webp")]
        fresh, (sw, sh), src_text = _fresh_rgb(j["src"])
        q = int(j.get("quality", 82))

        full = fresh.copy()
        full.thumbnail((int(j["max_full"]), int(j["max_full"])), Image.LANCZOS)
        # Pillow 12 WebPImagePlugin._save (lines 287-293) reads icc_profile / exif / xmp from
        # im.encoderinfo -- the save() kwargs -- and never from im.info. We pass none, and `fresh`
        # was built with Image.new so it carries no info either. The gate harness asserts this on
        # the emitted bytes (RIFF chunk list) rather than trusting the reading.
        full.save(j["full"], "WEBP", quality=q, method=6)

        thumb = fresh.copy()
        thumb.thumbnail((int(j["max_thumb"]), int(j["max_thumb"])), Image.LANCZOS)
        thumb.save(j["thumb"], "WEBP", quality=q, method=6)

        import os
        print(json.dumps({
            "base": base,
            "src_w": sw, "src_h": sh, "src_text_chunks": src_text,
            "full_w": full.size[0], "full_h": full.size[1], "full_bytes": os.path.getsize(j["full"]),
            "thumb_w": thumb.size[0], "thumb_h": thumb.size[1], "thumb_bytes": os.path.getsize(j["thumb"]),
        }, sort_keys=True))
    return 0


def png_chunks(data):
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    out, pos = [], 8
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        ctype = data[pos + 4:pos + 8].decode("latin-1")
        out.append(ctype)
        pos += 12 + length
    return out


def webp_chunks(data):
    if data[:4] != b"RIFF" or data[8:12] != b"WEBP":
        raise ValueError("not a WebP")
    out, pos = [], 12
    while pos + 8 <= len(data):
        fourcc = data[pos:pos + 4].decode("latin-1")
        size = struct.unpack("<I", data[pos + 4:pos + 8])[0]
        out.append(fourcc.rstrip())
        pos += 8 + size + (size & 1)
    return out


def cmd_chunks(path):
    with open(path, "rb") as fh:
        data = fh.read()
    if data[:4] == b"RIFF":
        kind, chunks = "webp", webp_chunks(data)
    else:
        kind, chunks = "png", png_chunks(data)
    print(json.dumps({"file": path, "kind": kind, "chunks": chunks, "bytes": len(data)}))
    return 0


def _normalised_rgb(path):
    """Decode to pixels: orientation applied, ICC converted to sRGB, RGB mode. Returns (img, info)."""
    import io
    from PIL import ImageCms, ImageOps
    im = Image.open(path)
    im.load()
    info_keys = sorted(str(k) for k in im.info.keys())
    had_icc = bool(im.info.get("icc_profile"))
    im = ImageOps.exif_transpose(im)
    if had_icc:
        src_prof = ImageCms.ImageCmsProfile(io.BytesIO(im.info["icc_profile"]))
        dst_prof = ImageCms.createProfile("sRGB")
        base = im.convert("RGBA" if "A" in im.getbands() else "RGB")
        im = ImageCms.profileToProfile(base, src_prof, dst_prof, outputMode=base.mode)
    if im.mode != "RGB":
        rgba = im.convert("RGBA")
        bg = Image.new("RGB", rgba.size, (255, 255, 255))
        bg.paste(rgba, mask=rgba.getchannel("A"))
        im = bg
    fresh = Image.new("RGB", im.size)
    fresh.paste(im)
    return fresh, {"src_w": im.size[0], "src_h": im.size[1], "info_keys": info_keys, "icc_converted": had_icc}


def cmd_pair(jobs_path):
    """One JSON line per pair. Target size = the LOCAL image fitted inside max_side, applied to both."""
    import os
    from PIL import ImageOps
    with open(jobs_path, "r", encoding="utf-8") as fh:
        jobs = json.load(fh)
    if isinstance(jobs, dict):
        jobs = [jobs]
    for j in jobs:
        local, linfo = _normalised_rgb(j["local"])
        remote, rinfo = _normalised_rgb(j["remote"])
        m = int(j["max_side"])
        lw, lh = local.size
        k = min(1.0, m / max(lw, lh))
        tw, th = max(1, round(lw * k)), max(1, round(lh * k))
        q = int(j["quality"])
        outs = {}
        for role, img in (("local", local), ("remote", remote)):
            fitted = ImageOps.fit(img, (tw, th), Image.LANCZOS, centering=(0.5, 0.5))
            buf = Image.new("RGB", fitted.size)
            buf.paste(fitted)
            dst = j["out_a"] if (role == "local") == bool(j["local_is_a"]) else j["out_b"]
            buf.save(dst, "WEBP", quality=q, method=6)
            outs[role] = dst
        print(json.dumps({
            "pair": j["pair"], "w": tw, "h": th,
            "a_bytes": os.path.getsize(j["out_a"]), "b_bytes": os.path.getsize(j["out_b"]),
            "local_src": [linfo["src_w"], linfo["src_h"]], "remote_src": [rinfo["src_w"], rinfo["src_h"]],
            "local_info_keys": linfo["info_keys"], "remote_info_keys": rinfo["info_keys"],
            "remote_icc_converted": rinfo["icc_converted"],
        }, sort_keys=True))
    return 0


def cmd_plant_provenance(src, dst, w, h, label):
    import io
    from PIL import ImageCms
    im = Image.open(src).convert("RGB").resize((int(w), int(h)), Image.LANCZOS)
    meta = PngImagePlugin.PngInfo()
    meta.add_text("Software", label)
    meta.add_itxt("XML:com.adobe.xmp", '<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:Description CreatorTool="%s"/></x:xmpmeta>' % label)
    # C2PA manifests ride in PNG as a caBX chunk holding a JUMBF box ('jumb' / 'jumd' ... 'c2pa').
    jumbf = b"\x00\x00\x00\x40jumb\x00\x00\x00\x18jumdc2pa\x00\x11\x00\x10\x80\x00\xaa\x00\x38\x9b\x71c2pa\x00" + label.encode("utf-8")
    meta.add(b"caBX", jumbf)
    exif = Image.Exif()
    exif[0x0131] = label          # Software
    exif[0x010E] = label          # ImageDescription
    exif[0x0112] = 1              # Orientation
    icc = ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes()
    im.save(dst, "PNG", pnginfo=meta, exif=exif.tobytes(), icc_profile=icc)
    print(json.dumps({"planted": dst, "label": label}))
    return 0


def cmd_plant(src, dst, key, text):
    im = Image.open(src)
    im.load()
    meta = PngImagePlugin.PngInfo()
    meta.add_text(key, text)
    im.save(dst, "PNG", pnginfo=meta)
    print(json.dumps({"planted": dst, "key": key}))
    return 0


def main(argv):
    if len(argv) >= 3 and argv[0] == "encode" and argv[1] == "--jobs":
        return cmd_encode(argv[2])
    if len(argv) == 2 and argv[0] == "chunks":
        return cmd_chunks(argv[1])
    if len(argv) >= 3 and argv[0] == "pair" and argv[1] == "--jobs":
        return cmd_pair(argv[2])
    if len(argv) == 6 and argv[0] == "plant-provenance":
        return cmd_plant_provenance(argv[1], argv[2], argv[3], argv[4], argv[5])
    if len(argv) == 5 and argv[0] == "plant":
        return cmd_plant(argv[1], argv[2], argv[3], argv[4])
    sys.stderr.write(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
